/*let text = "This is a string";
console.log(text.substring(2));
console.log(text.substring(5));
console.log(text.substring(12));
console.log(text.substring(20));*/
/*let people ="Hello";
console.log(people.substring(0));
console.log(people.substring(1));
console.log(people.substring(2));
console.log(people.substring(3));
console.log(people.substring(4));*/
/*let rasturant = "pizza";
console.log(rasturant.substring(0));
console.log(rasturant.substring(1));
console.log(rasturant.substring(2));
console.log(rasturant.substring(3));
console.log(rasturant.substring(4));*/
/*let Helloween = "pumpkin";
console.log(Helloween.substring(0));
console.log(Helloween.substring(1));
console.log(Helloween.substring(2));
console.log(Helloween.substring(3));
console.log(Helloween.substring(4));
console.log(Helloween.substring(5));
console.log(Helloween.substring(6));*/
